kumuluzee:
  name: uniborrow-reviews-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-location: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ReviewsDB
      connection-url: jdbc:postgresql://localhost:5432/reviews
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ReviewsDB
