kumuluzee:
  name: uniborrow-reviews-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ReviewsDB
      connection-url: jdbc:postgresql://localhost:5432/reviews
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ReviewsDB
      etcd-health-check:
        connection-url: http://localhost:2379/health
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: 'http://localhost:2379'
  discovery:
    etcd:
      hosts: 'http://localhost:2379'
  metrics:
    servlet:
      enabled: true
      mapping: /metrics/*
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /metrics/*
        status-codes: "200, 500"
      - name: user-reviews-endpoint
        url-pattern: /v1/users*
        status-codes: "200, 500"
      - name: item-reviews-endpoint
        url-pattern: /v1/items*
        status-codes: "200, 500"
  rest-client:
    registrations:
      - class: uniborrow-users-api
        read-timeout: 5000
      - class: uniborrow-items-api
        read-timeout: 5000
  openapi-mp:
    enabled: true
    servlet:
      mapping: /uniborrow-reviews-openapi
    ui:
      enabled: true
      mapping: /uniborrow-reviews-openapi/ui
      specification-server: http://localhost:8080/
  dev:
    scan-libraries:
      - reviews-lib
  log:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="252bc561-0bda-442f-97f3-ba3d8b1a720d-ls.logit.io"
                                    port="18623" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
admin-properties:
  disable-items: false
  disable-users: false